services:
  # ETL Service 
  etl-service:
    build:
      context: ./etl
      dockerfile: Dockerfile.etl
    environment:
      JUPYTER_ENABLE_LAB: "yes" 
    ports:
      - "8888:8888" 
    volumes:
      - ./etl:/app 
      - ./data:/app/data     
    command: ["spark-submit", "/app/ingest_and_process.py"]
volumes:
  etl-service: